export const apiRoutes = {
  videos: {
    getAllContentByType: "/videos/get-all-content-by-type",
    getVideoById: "/videos/get-video/",
    uploadVideo: "/videos/upload-video",
    getAllUserContentByType: "/videos/get-all-user-content-by-type",
    updateVideo: "/videos/update-video/",
    deleteVideo: "/videos/delete-video",
    makeACopy: "/videos/make-copy",
    getVideoByUserId: "/videos/get-video-by-user-id",
    getAllShorts: "/videos/get-all-shorts",
    getAllSearchContent: "/videos/get-all-search-content",
    updateViewCount: "/videos/update-view-count/",
  },
  users: {
    register: "/users/register",
    verifyAccount: "/users/verify-user",
    getCurrentUser: "/users/user",
    resetPassword: "/users/reset-password",
    forgotPassword: "/users/forgot-password",
    changeCurrentPassword: "/users/change-current-password",
    updateUserDetails: "/users/update-user-account-details",
    updateAvatar: "/users/update-avatar",
    updateCoverImage: "/users/update-cover-image",
    login: "/users/login",
    logout: "/users/logout",
    getUser: "/users/user",
    getAllChannelFollower: "/users/get-all-channel-subscriber",
    getChannelAnalytics: "/users/get-channel-analytics",
    addedWatchHistory: "/users/added-watch-history",
    watchHistory: "/users/watch-history",
    deleteWatchHistory: "/users/delete-watch-history",
  },
  posts: {
    getAllUserPosts: "/tweets/get-all-user-tweets",
    createPost: "/tweets/create-tweet",
    updatePost: "/tweets/update-tweet/",
    deletePost: "/tweets/delete-tweet",
  },
  comments: {
    createComment: "/comments/create-comment",
    updateComment: "/comments/update-comment",
    deleteComment: "/comments/delete-comment",
    getAllCommentById: "/comments/get-all-comment-by-id/",
  },
  playlists: {
    getAllPlaylists: "/playlists/get-all-playlists",
    getPlaylistById: "/playlists",
    getPlaylistByUserId: "/playlists/get-all-playlist-by-user-id",
    createPlaylist: "/playlists/create-playlist",
    updatePlaylist: "/playlists/update-playlist/",
    deletePlaylist: "/playlists/delete-playlist",
  },
  likes: {
    getUserLikeVideos: "/likes/get-user-like-videos",
    likeDislike: "/likes/like-dislike",
  },
  follows: {
    createFollowAndUnfollow: "/subscriptions/create-subscribe-and-unsubscribe",
    getAllFollowingChannel: "/subscriptions/get-all-subscribed-channel",
  },
};

export type IRoutesKeys = (typeof apiRoutes)[keyof typeof apiRoutes];
